### PR TITLE
adding ability to move to specific position from current model location

### PR DESCRIPTION
**Pull request by fuzzybaird**
It would be nice to add a method on the trait that allows people to move a specific location. 

My proposed method.

```php
$myModel->moveToPosition($postion);
```
I have created a working implementation and attached it to the PR. Please let me know if there are any questions or concerns.

### CODE REVIEW

**Comment by pjhartin** [comment]
I would love to see this merged

**Comment by freekmurze** [comment]
Thank you for work your work on this, but I'm not going to merge it, as I don't have a need for this function myself. My concern is also that it could cause a lot of updates for tables with a large number of rows.

**Comment by fuzzybaird** [comment]
@freekmurze thanks for the feedback, I understand your concern, it is my understanding that this functionality has been pretty optimized in SQL. Given that this is default Laravel behavior with the increment or decrement functionality, I assumed people could use at their own risk; we could also give a disclaimer on the documentation if you would like. If you are still disinterested I understand and appreciate you for at least considering it.

**Comment by pjhartin** [comment]
@fuzzybaird - The use case you describe is exactly the functionality that is required for a product I am working on right now, and the moveToPosition is very performant. At the moment, because it has not been merged, I am adding the method to each model that requires it. 

Is there a cleaner way for me to do this, as I cannot extend the existing Sortable trait.

**Comment by fuzzybaird** [comment]
@pjhartin  you could reference my feature branch directly in your composer file, as a temporary solution, or create your own branch and do the same. I understand why @freekmurze declined the PR. It could be a performance risk, and since I do not have exact performance data so I am happy to let this one lie. I personally think that there needs to be a package that uses floats and fractions that accommodates movable priority so the sql implications to shifting a priority are isolated to a few rows vs potentially an entire table. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
