### PR TITLE
[FEAT] add withoutGlobalScopes to setNewOrder method

### PR DESCRIPTION
**Pull request by AbdelrahmanBl**

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests for this and update the readme with an example?

**Comment by AbdelrahmanBl** [comment]
Hello sir, i had been added tests and updated the readme file with an example.

**Comment by freekmurze** [comment]
Although the implementation is now technically correct, I think we could create a more dynamic solution for this.

Instead of adding a parameter to pass an array of global scopes, let's pass a closure (parameter name could be `$modifyQuery`). In our code, we would pass the query to that closure, so the user can modify the query in any way (and not just only removing global scopes).

Could you perform these modifications?

**Comment by AbdelrahmanBl** [comment]
Good evening sir, can you check these updates.

**Comment by AbdelrahmanBl** [comment]
Yes, it's my mistake can you check for now.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
