### PR TITLE
Add Feature: sorting scopes

### PR DESCRIPTION
**Pull request by zoomyboy**
As I'm still working with Laravel 5.2, I created a fork of the 2.3.0 version. I found this feature useful, because I wanted to allow a user to sort his comments of a post - so I created a sort_scope to prevent sorting comments of other users.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thanks for you PR.

However I'm not going to merge it in because I want to keep this package as small as possible and don't think the feature is important enough.

**Comment by danielstgt** [comment]
This package can come in very handy, thank you! Although it’s limited to models without relation... which is the reason why I’m throwing up this old PR again.

Scoping the sorting functionality would be great for hasMany relations, I think that’s a very common scenario to get sorting grouped by a foreign key.

@freekmurze  any plans on re-evaluating the decision to reject this PR?

It’s by far the most requested feature:

PRs including this one:
#36 
#56 
#38 
#48 

Issues:
#54 
#37 
#2

**Comment by freekmurze** [comment]
I might reconsider this if there is a very very simple, well documented, well tested PR that adds this.

**Comment by pierrocknroll** [comment]
I achieved this with this simple code, I extends the SortableTrait method within my Model :
```php
    public function buildSortQuery()
    {
        return static::query()->where('parent_id', $this->parent_id);
    }
```

**Comment by NioTeX** [comment]
Exactly what I was looking for, thanks @pierrocknroll 
This works great with https://github.com/Naxon/nova-field-sortable to sort hasMany relations in Laravel Nova

**Comment by Yahav** [comment]
@freekmurze if you're not going to address this issue, the solution given by @pierrocknroll  should at the very least be documented!

**Comment by freekmurze** [comment]
@Yahav feel free to send a PR.

**Comment by Yelles** [comment]
> I achieved this with this simple code, I extends the SortableTrait method within my Model :
> 
> ```
>     public function buildSortQuery()
>     {
>         return static::query()->where('parent_id', $this->parent_id);
>     }
> ```

Hi,

Your PR could work with relation order?
I have two tables (products and groups), i need to list products sorted by the sort_order of the group, then the product sort_order.

product_id | group_id | name | sort_order
------------ | ------------- | ------------- | -------------
1 | 1 | test | 1
2 |  2 | test | 2
3 | 1 | test | 3

group_id | name | sort_order
------------ | ------------- | -------------
1 | group1 | 2
2 | group1 | 1

**Comment by agueric** [comment]
> I achieved this with this simple code, I extends the SortableTrait method within my Model :
> 
> ```
>     public function buildSortQuery()
>     {
>         return static::query()->where('parent_id', $this->parent_id);
>     }
> ```

Hi. I tried to do the same but it seems that the function is not being even read. I implemented the function in my model:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;
use Spatie\Activitylog\Traits\LogsActivity;

class Campaign extends Model implements Sortable
{
use SortableTrait;
    protected $table = 'campaigns';
    public $sortable = [
        'order_column_name' => 'priority',
        'sort_when_creating' => true,
    ];
   public function buildSortQuery()
    {
        return static::query()->where('parent_id', $this->parent_id);
    }
}

```
Could someone please point me on the right direction?
I'm using Laravel 5.7 & PHP7.0

**Comment by pierrocknroll** [comment]
Hello @agueric 
The buildSortQuery method is called when you use moveToEnd, getHighestOrderNumber, moveOrderDown, moveOrderUp, moveToStart methods

**Pull request closed without merging**
