### PR TITLE
Support laravel 11

### PR DESCRIPTION
**Pull request by mokhosh**

### CODE REVIEW

**Comment by mokhosh** [comment]
Failing tests are related to ignoring timestamps on `prefer lowest` which I will submit a PR to fix separately.

**Comment by mokhosh** [comment]
@freekmurze can we merge this before I fix the workflows? Because that one also needs a change in the same composer.json lines and it would create a merge conflict.

**Comment by freekmurze** [comment]
Sure, awaiting your next PR.

**Comment by mokhosh** [comment]
Thanks, here you go https://github.com/spatie/eloquent-sortable/pull/173

**Pull request merged**
