### PR TITLE
Solving moveToEnd bug when using grouping field (#103)

### PR DESCRIPTION
**Pull request by giovanniledda**
Explanation can be found on issue #103

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test to make sure this change works as expected?

**Comment by giovanniledda** [comment]
> Could you add a test to make sure this change works as expected?

Ok, I'll try..

**Comment by freekmurze** [comment]
Since the behaviour changes, I'm going to treat this as a breaking change.

That means that I'm not going to merge it in for now, but review it when working on a next major release.

**Comment by giovanniledda** [comment]
Ok, that's fine. Thanks!

Il giorno ven 12 feb 2021 alle ore 08:17 Freek Van der Herten <
notifications@github.com> ha scritto:

**Comment by will-dive** [comment]
@freekmurze Is it possible that this PR has been forgotten about? We encountered this bug recently and implemented @giovanniledda's solution and it seems to work quite nicely.

**Comment by LorensoD** [comment]
I'm also experiencing this bug currently. @giovanniledda's solution indeed seems to work.

**Pull request closed without merging**
